server:
  port: ${AUTH_SERVER_PORT:9000}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:PetProject}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}

app:
  authentication:
    server:
      client-id: ${AUTH_SERVER_CLIENT_ID:custom-client}
      client-secret: ${AUTH_SERVER_CLIENT_SECRET:secret}
      redirect-uri: ${AUTH_SERVER_REDIRECT_URI:http://127.0.0.1:8081/login/oauth2/code/custom-client-oidc}
