server:
  port: ${BATTLE_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:PetProject}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jws-algorithms: RSA

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  vars:
    statistic:
      url: http://${STATISTIC_HOST:localhost}:${STATISTIC_PORT:8082}
