version: '3'
services:
  pp-mysql:
    hostname: pp-mysql
    container_name: pp-mysql
    image: mysql:5.7.32
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
       MYSQL_ROOT_PASSWORD: $DB_PASSWORD
       MYSQL_USER: $DB_USERNAME
       MYSQL_PASSWORD: $DB_PASSWORD
       MYSQL_DATABASE: $DB_NAME
    networks:
      - pp-network

  pp-battle:
    container_name: pp-battle
    build:
      context: /battle-service
      dockerfile: /Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BATTLE_PORT}:${BATTLE_PORT}
    depends_on:
      - pp-mysql
    networks:
      - pp-network

  pp-user:
    container_name: pp-user
    build:
      context: /user-service
      dockerfile: /Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${USER_PORT}:${USER_PORT}
    depends_on:
      - pp-mysql
    networks:
      - pp-network

  pp-statistic:
    container_name: pp-statistic
    build:
      context: /statistic-service
      dockerfile: /Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${STATISTIC_PORT}:${STATISTIC_PORT}
    depends_on:
      - pp-mysql
    networks:
      - pp-network

  pp-auth-server:
    container_name: pp-auth-server
    build:
      context: /auth-service
      dockerfile: /Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}
    depends_on:
      - pp-mysql
    networks:
      - pp-network

networks:
  pp-network:
    driver: bridge
    ipam:
      driver: default
