server:
  port: ${STATISTIC_PORT:8082}

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/PetProject_Statistic}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: statisticDto:by.pashkevich.mikhail.dto.StatisticDto

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
