server:
  port: ${STATISTIC_PORT:8082}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME:root}:${MONGO_DB_PASSWORD:12345}@${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/${MONGO_DB_NAME:PetProject_Statistic}?authMechanism=SCRAM-SHA-1&authSource=admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
