server:
  port: ${STATISTIC_PORT:8082}

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/PetProject_Statistic}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
